#!/usr/bin/ksh93
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2026 The illumos DRM Authors
#

#
# upstream-sync.sh -- Copy DRM sources from a Linux kernel tree into
# gfx-drm, preserving illumos-specific shim files.
#
# Usage: upstream-sync.sh <linux-kernel-source-path>
#
# The script:
#   1. Validates the Linux tree
#   2. Records the sync point (git hash, version, date)
#   3. Copies DRM core .c files to usr/src/uts/common/io/drm/
#   4. Copies DRM headers to usr/src/uts/common/drm/
#   5. Copies reference files (dma-buf, kernel-internal headers)
#   6. Never overwrites illumos-specific shim files
#

set -o errexit
set -o pipefail

PROGNAME=${0##*/}
LINUX_SRC="$1"

# Paths relative to gfx-drm root
DRM_SRC="usr/src/uts/common/io/drm"
DRM_HDR="usr/src/uts/common/drm"
LINUX_REF="${DRM_SRC}/linux-ref"
SYNC_FILE="LINUX_UPSTREAM_SYNC"

# Files that must NEVER be overwritten (illumos shim layer)
PROTECTED_SRC=(
	drm_sun_i2c.c
	drm_sun_idr.c
	drm_sun_pci.c
	drm_sun_timer.c
	drm_sun_workqueue.c
	drm_sun_ww_mutex.c
	drm_sun_dma_fence.c
	drm_sun_dma_fence_array.c
	drm_sun_dma_resv.c
	drm_sunmod.c
	drm_io32.c
	drm_kstat.c
	drm_linux.c
	drm_msg.c
	drm_dp_i2c_helper.c
)

PROTECTED_HDR=(
	drm_sun_ref.h
	drm_sun_i2c.h
	drm_sun_idr.h
	drm_sun_pci.h
	drm_sun_timer.h
	drm_sun_workqueue.h
	drm_sun_ww_mutex.h
	drm_sun_dma_fence.h
	drm_sun_dma_fence_array.h
	drm_sun_dma_resv.h
	drm_os_solaris.h
	drm_linux.h
	drm_linux_list.h
	drm_io32.h
	drm_sunmod.h
	drmP.h
)

# Linux-only files we never want (no illumos equivalent)
EXCLUDED_SRC=(
	drm_debugfs.c
	drm_debugfs_crc.c
	drm_sysfs.c
	drm_panic.c
	drm_panic_qr.c
	drm_of.c
	drm_mipi_dsi.c
	drm_mipi_dbi.c
	drm_client_sysrq.c
)

die() {
	print -u2 "${PROGNAME}: $*"
	exit 1
}

info() {
	print ">> $*"
}

is_protected_src() {
	typeset f="$1"
	typeset p
	for p in "${PROTECTED_SRC[@]}"; do
		[[ "$f" == "$p" ]] && return 0
	done
	# Also protect anything matching drm_sun_*
	[[ "$f" == drm_sun_* ]] && return 0
	return 1
}

is_protected_hdr() {
	typeset f="$1"
	typeset p
	for p in "${PROTECTED_HDR[@]}"; do
		[[ "$f" == "$p" ]] && return 0
	done
	[[ "$f" == drm_sun_* ]] && return 0
	return 1
}

is_excluded_src() {
	typeset f="$1"
	typeset p
	for p in "${EXCLUDED_SRC[@]}"; do
		[[ "$f" == "$p" ]] && return 0
	done
	# Exclude patterns
	[[ "$f" == drm_fbdev_* ]] && return 0
	[[ "$f" == drm_privacy_screen* ]] && return 0
	return 1
}

#
# Validate arguments
#
[[ -z "$LINUX_SRC" ]] && die "Usage: $PROGNAME <linux-kernel-source-path>"
[[ -d "$LINUX_SRC/drivers/gpu/drm" ]] || \
    die "Not a Linux kernel tree: $LINUX_SRC (missing drivers/gpu/drm)"

#
# Must be run from gfx-drm root
#
[[ -f "Makefile" && -d "usr/src/uts/common/io/drm" ]] || \
    die "Must be run from the gfx-drm repository root"

#
# Record sync point
#
typeset linux_commit linux_version sync_date
if [[ -d "${LINUX_SRC}/.git" ]]; then
	linux_commit=$(git -C "$LINUX_SRC" rev-parse HEAD 2>/dev/null || echo "unknown")
	linux_version=$(git -C "$LINUX_SRC" describe --tags --always 2>/dev/null || echo "unknown")
else
	linux_commit="unknown"
	linux_version="unknown"
fi
sync_date=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

cat > "$SYNC_FILE" <<EOF
# Linux DRM upstream sync record
# Generated by tools/upstream-sync.sh -- do not edit manually
LINUX_COMMIT=${linux_commit}
LINUX_VERSION=${linux_version}
SYNC_DATE=${sync_date}
EOF

info "Sync from Linux ${linux_version} (${linux_commit:0:12})"

#
# Counters
#
typeset -i copied=0 protected=0 excluded=0 new_files=0

#
# Copy DRM core .c files
#
info "Copying DRM core sources..."
for src in "${LINUX_SRC}"/drivers/gpu/drm/*.c; do
	f=$(basename "$src")

	if is_protected_src "$f"; then
		(( protected++ ))
		continue
	fi

	if is_excluded_src "$f"; then
		(( excluded++ ))
		continue
	fi

	[[ ! -f "${DRM_SRC}/${f}" ]] && (( new_files++ ))
	cp "$src" "${DRM_SRC}/${f}"
	(( copied++ ))
done

#
# Copy DRM headers
#
info "Copying DRM headers..."
for hdr in "${LINUX_SRC}"/include/drm/*.h; do
	f=$(basename "$hdr")

	if is_protected_hdr "$f"; then
		(( protected++ ))
		continue
	fi

	[[ ! -f "${DRM_HDR}/${f}" ]] && (( new_files++ ))
	cp "$hdr" "${DRM_HDR}/${f}"
	(( copied++ ))
done

#
# Copy Linux reference files (dma-buf, kernel-internal headers)
#
info "Copying Linux reference files..."
mkdir -p "$LINUX_REF"

# dma-buf implementation files
for ref in \
    "${LINUX_SRC}"/drivers/dma-buf/dma-fence.c \
    "${LINUX_SRC}"/drivers/dma-buf/dma-fence-array.c \
    "${LINUX_SRC}"/drivers/dma-buf/dma-fence-chain.c \
    "${LINUX_SRC}"/drivers/dma-buf/dma-fence-unwrap.c \
    "${LINUX_SRC}"/drivers/dma-buf/dma-resv.c \
    "${LINUX_SRC}"/drivers/dma-buf/dma-buf.c \
    "${LINUX_SRC}"/include/linux/dma-fence.h \
    "${LINUX_SRC}"/include/linux/dma-fence-array.h \
    "${LINUX_SRC}"/include/linux/dma-fence-chain.h \
    "${LINUX_SRC}"/include/linux/dma-fence-unwrap.h \
    "${LINUX_SRC}"/include/linux/dma-resv.h \
    "${LINUX_SRC}"/include/linux/dma-buf.h \
    "${LINUX_SRC}"/include/linux/ww_mutex.h; do
	[[ -f "$ref" ]] && cp "$ref" "${LINUX_REF}/" && (( copied++ ))
done

cat > "${LINUX_REF}/README" <<'EOF'
These are unmodified Linux kernel source files, included for reference only.
They are NOT compiled -- the illumos equivalents are the drm_sun_* shim files.

To update: run `make upstream-sync LINUX_SRC=/path/to/linux`
EOF

#
# Summary
#
info ""
info "=== Upstream Sync Complete ==="
info "  Linux version: ${linux_version}"
info "  Files copied:    ${copied}"
info "  Files protected: ${protected} (illumos shim files)"
info "  Files excluded:  ${excluded} (no illumos equivalent)"
info "  New files:       ${new_files} (not previously in gfx-drm)"
info ""
info "  Sync record:     ${SYNC_FILE}"
info "  Linux reference:  ${LINUX_REF}/"
info ""
info "Next steps:"
info "  1. Review changes: git diff"
info "  2. Update Makefile.mod if new .c files were added"
info "  3. Fix up shim layer (drm_linux.h, drmP.h, drm_sun_*.c)"
info "  4. Build: make debug"
